### ISSUE TITLE
tests failed when running on docker gitlab ci

### ISSUE THREAD

**Issue by giedriusramas** [certtools/intelmq#1596]
here is my .gitlab-ci.yml
```
.python38: &python38
  image:
    name: python:3.8
    entrypoint: [""]
  tags:
    - docker

.ubuntu: &ubuntu
  image:
    name: ubuntu
    entrypoint: [""]
  tags:
    - docker    

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

test:
  <<: *ubuntu
  stage: test
  before_script:
    - apt-get update
    - apt-get install python3 python3-pip redis git -y
    - /etc/init.d/redis-server start
    - pip3 install Cerberus PyYAML
    - adduser --disabled-password --gecos "" intelmq
  script:
    - INTELMQ_SKIP_INTERNET=1 python3 setup.py test

build:
  <<: *python38
  stage: build
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl

stages:
  - test
  - build

```

and tests are failing for develop branch

https://gist.githubusercontent.com/giedriusramas/dc9d7a4472a96da0ce1373a684ce1433/raw/e43a75870bfbb8aa4f44f92c46d2edcdd5799596/gistfile1.txt

anyone has an idea what might I am missing ?
