### ISSUE TITLE
Install in persistent mode the Stomp library in a intelMQ-Manager docker compose instance

### ISSUE THREAD

**Issue by ludoComp9** [certtools/intelmq#2356]
Hello,

I have a stupid question. My IntelMQ instance is running from following docker-compose.yml file:
```
version: "3"
services:
    redis:
        container_name: intelmq-redis
        image: redis:latest
        volumes:
            - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
        restart: always
        networks:
            - internal
    nginx:
        container_name: intelmq-nginx
        image: certat/intelmq-nginx:latest
        restart: always
        ports:
            - 1337:80
        depends_on:
            - intelmq
        networks:
            - internal
    intelmq:
        container_name: intelmq
        image: certat/intelmq-full:latest
        volumes:
            - ./config/intelmq/etc/:/opt/intelmq/etc/
            - ./config/intelmq-api/config.json:/etc/intelmq/api-config.json
            - ./logs:/opt/intelmq/var/log
            - ./output:/opt/intelmq/var/lib/bots
        depends_on:
            - redis
        environment:
            INTELMQ_SOURCE_PIPELINE_BROKER: "redis"
            INTELMQ_PIPELINE_BROKER: "redis"
            INTELMQ_DESTIONATION_PIPELINE_BROKER: "redis"
            INTELMQ_PIPELINE_HOST: redis
            INTELMQ_SOURCE_PIPELINE_HOST: redis
            INTELMQ_DESTINATION_PIPELINE_HOST: redis
            INTELMQ_REDIS_CACHE_HOST: redis
        networks:
            - internal

networks:
    internal:
        driver: bridge
```

How to apply persistent pip3 install -r intelmq/bots/collectors/stomp/REQUIREMENTS.txt ? Rebuild "intelmq" container in docker-compose.yml adding build parameter to launch a Dockerfile with pip command before to launch intelmq ?
Some bot collectors requires to install IntelMQ as package in Linux system instead of docker compose ?

Regards,
